[customizations.installer.modules]
enable = ["org.fedoraproject.Anaconda.Modules.Localization"]

[customizations.installer.kickstart]
contents = """
lang fr_BE.UTF-8
keyboard --vckeymap=be-latin1 --xlayouts='fr'
timezone Europe/Brussels

firewall --use-system-defaults

zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --type=lvm --encrypted --passphrase=PLACEHOLDER --luks-version=luks2

network --bootproto=dhcp --onboot=yes --activate

rootpw --lock

reboot --eject

%post --erroronfail --log=/root/anaconda-post.log

systemctl set-default graphical.target
bootc switch --mutate-in-place --transport registry <IMAGE_SIGNED> <UPDATE_IMAGE_REF>
%end
"""
