[Interface]
Address = PLACEHOLDER_CLIENT_ADDRESS
PrivateKey = PLACEHOLDER_PRIVATE_KEY
DNS = 1.1.1.1

[Peer]
AllowedIPs = GH_SEC_WG_ALLOWEDIPS
PublicKey = GH_SEC_WG_PUBLIC_KEY
Endpoint = GH_SEC_WG_ENDPOINT
PresharedKey = PLACEHOLDER_PRESHARED_KEY
PersistentKeepalive = 25
